### ISSUE TITLE
Using __future__ annotations seems to break it

### ISSUE THREAD

**Issue by wardy3** [philipp-mohr/dataclass-persistence#1] opened 2021-04-05 05:38 UTC
if
```python
from __future__ import annotations
```

is at the top of the file, the example only yields:
```
SomeData(parameter_a=None, array=None)
```

Comment it out and it gets the expected
```
SomeData(parameter_a='my_string', array=array([0, 0]))
```

The json.zip file seems to have the data but it doesn't get loaded back in. 

I think it's because the `__future__` import changes some things in the dataclass fields

Works:
```
_fields=[('my_string', Field(name='parameter_a',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x109370ac0>,default_factory=<dataclasses._MISSING_TYPE object at 0x109370ac0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD)), ({'data': [0, 0], 'dtype': 'int64'}, Field(name='array',type=<class 'numpy.ndarray'>,default=<dataclasses._MISSING_TYPE object at 0x109370ac0>,default_factory=<dataclasses._MISSING_TYPE object at 0x109370ac0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD))]
```
Doesn't work:
```
_fields=[('my_string', Field(name='parameter_a',type='str',default=<dataclasses._MISSING_TYPE object at 0x1015933d0>,default_factory=<dataclasses._MISSING_TYPE object at 0x1015933d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD)), ({'data': [0, 0], 'dtype': 'int64'}, Field(name='array',type='np.ndarray',default=<dataclasses._MISSING_TYPE object at 0x1015933d0>,default_factory=<dataclasses._MISSING_TYPE object at 0x1015933d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD))]
```
Note how `__future__` seems to change `type=<class 'str'>` into `type=str`

This breaks your 
```python
    elif type_instance in built_in_types:
```
```
ipdb> built_in_types
[<class 'int'>, <class 'float'>, <class 'str'>, <class 'bool'>, <class 'complex'>, <class 'NoneType'>]
ipdb> type_instance
'str'
```
and since there's no `else` it just returns None

**Comment by philipp-mohr** [comment] 2021-04-06 15:48
The issue is now fixed in version 0.0.8. Thanks for reporting.

**Closed as completed** 2021-04-06 15:48 UTC
